baseURL = "https://davidlaschhvac.com"
languageCode = "en-us"
title = "David Lasch Heating and Air Conditioning"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[markup.goldmark.renderer]
  unsafe= true
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/logo.svg"
    desktop_height = "60px"
    desktop_width = "215px"
    alt = "David Lasch HVAC"

  [params.homepage_meta_tags]
    meta_description = "Your top choice for home & business heating, ventilation, AC solutions. Offers repairs, installations, maintenance, inspections, & indoor air quality enhancement."
    meta_og_title = "David Lasch HVAC"
    meta_og_type = "website"
    meta_og_url = "https://davidlaschhvac.com"
    meta_og_image = "https://raw.githubusercontent.com/s-lasch/hvac-website/master/images/tn.png"
    meta_og_description = "Your top choice for home & business heating, ventilation, AC solutions. Offers repairs, installations, maintenance, inspections, & indoor air quality enhancement."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "About"
	url = "/about/"
    weight = 1

[[menu.main]]
    name = "Appliances"
    url = "/appliances/"
    weight = 2

[[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

# [[menu.main]]
#     name = "History"
#     url = "/history/"
#     weight = 3

# [[menu.main]]
#     name = "Work"
#     url = "/work/"
#     weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
